/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import DBA.FileKhoaVien;
import ENTITY.DiemMonHoc;
import ENTITY.KhoaVien;
import ENTITY.LopHoc;
import ENTITY.MonHoc;
import ENTITY.MonTinChi;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author tu
 */
public class ThemMonTinChiGUI extends javax.swing.JFrame {

    /**
     * Creates new form ThemMonTinChiGUI
     */
    FileKhoaVien fileKhoaVien = new FileKhoaVien();
    DefaultComboBoxModel<String> boxModelMonHoc;
    public static String maVien;
    public ArrayList<MonHoc> listMonHocDK;
    public ThemMonTinChiGUI() {
        this.setVisible(true);
        this.setTitle("Thêm môn học tín chỉ");
        initComponents();
        btnThemMonDK.setEnabled(false);
        txtMaVien.setEnabled(false);
        initComboBoxTenMonHoc();
        txtMaVien.setText(maVien);
    }
    
    // Đổ dữ liệu cho ComboBox
    public void initComboBoxTenMonHoc(){
        boxModelMonHoc = new DefaultComboBoxModel<>();
        txtMaVien.setText(maVien); // Khởi tạo giá trị mã viện
        ArrayList<KhoaVien> listKhoaVien =  fileKhoaVien.docFileKhoaVien();
        ArrayList<MonHoc> listMonHoc = new ArrayList<>();
        for (KhoaVien khoaVien : listKhoaVien) {
            if (khoaVien.getMaKhoaVien().equals(maVien)){
                listMonHoc = khoaVien.getDsMonHoc();
            }
        }
        
        for (MonHoc monHoc : listMonHoc){
            if (monHoc instanceof MonTinChi){
                boxModelMonHoc.addElement(monHoc.getTenMon());
            }
        }
        
        cbTenMonHoc.setModel(boxModelMonHoc);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnThemMonDK = new javax.swing.JButton();
        btnThemMonHoc = new javax.swing.JButton();
        btnThoat = new javax.swing.JButton();
        checkboxDK = new javax.swing.JCheckBox();
        txtMaVien = new javax.swing.JTextField();
        txtMaMonHoc = new javax.swing.JTextField();
        txtTenMonHoc = new javax.swing.JTextField();
        cbTenMonHoc = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        txtSoTC = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(254, 254, 254));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setText("THÊM MÔN HỌC TÍN CHỈ");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel2.setText("Mã Viện: ");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel3.setText("Mã Môn Học : ");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel4.setText("Tên Môn Học : ");

        btnThemMonDK.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnThemMonDK.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGE/add50x50.png"))); // NOI18N
        btnThemMonDK.setText("Môn Học ĐK");
        btnThemMonDK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemMonDKActionPerformed(evt);
            }
        });

        btnThemMonHoc.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnThemMonHoc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGE/add50x50.png"))); // NOI18N
        btnThemMonHoc.setText("Thêm Môn Học");
        btnThemMonHoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemMonHocActionPerformed(evt);
            }
        });

        btnThoat.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnThoat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGE/exit.png"))); // NOI18N
        btnThoat.setText("Thoát");
        btnThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThoatActionPerformed(evt);
            }
        });

        checkboxDK.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        checkboxDK.setText("Môn Học Điều Kiện");
        checkboxDK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkboxDKActionPerformed(evt);
            }
        });

        cbTenMonHoc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel5.setText("Số Tín Chỉ : ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(139, 139, 139)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(33, 33, 33)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(checkboxDK)
                            .addComponent(cbTenMonHoc, 0, 214, Short.MAX_VALUE)
                            .addComponent(txtTenMonHoc)
                            .addComponent(txtMaMonHoc)
                            .addComponent(txtMaVien)
                            .addComponent(txtSoTC))))
                .addContainerGap(125, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnThemMonDK, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnThemMonHoc, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnThoat, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {cbTenMonHoc, txtMaMonHoc, txtMaVien, txtTenMonHoc});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMaVien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtMaMonHoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtTenMonHoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtSoTC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(checkboxDK)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnThemMonDK, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbTenMonHoc))
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThoat)
                    .addComponent(btnThemMonHoc))
                .addGap(24, 24, 24))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void checkboxDKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkboxDKActionPerformed
        // TODO add your handling code here:
        if(checkboxDK.isSelected()){
            btnThemMonDK.setEnabled(true);
        }else {
            btnThemMonDK.setEnabled(false);
        }
    }//GEN-LAST:event_checkboxDKActionPerformed

    private void btnThemMonDKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemMonDKActionPerformed
        // TODO add your handling code here:
        themMonHocDK();
    }//GEN-LAST:event_btnThemMonDKActionPerformed

    private void btnThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThoatActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnThoatActionPerformed

    private void btnThemMonHocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemMonHocActionPerformed
        // TODO add your handling code here:
        themMonHoc();
    }//GEN-LAST:event_btnThemMonHocActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ThemMonTinChiGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ThemMonTinChiGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ThemMonTinChiGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ThemMonTinChiGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ThemMonTinChiGUI().setVisible(true);
            }
        });
    }
    
    // Thêm môn học điều kiện vào list Môn Học Điều Kiện
    public void themMonHocDK(){
        listMonHocDK = new ArrayList<>();
        String tenMH = cbTenMonHoc.getSelectedItem().toString();
        
        ArrayList<KhoaVien> listKhoaVien = fileKhoaVien.docFileKhoaVien();
        ArrayList<MonHoc> listMH = null;
        for (KhoaVien khoaVien : listKhoaVien) {
            if (khoaVien.getMaKhoaVien().equals(maVien)){
                listMH = khoaVien.getDsMonHoc();
            }
        }
        
        for (MonHoc monHoc : listMH) {
            if (monHoc.getTenMon().equals(tenMH)){
                listMonHocDK.add(monHoc);
            }
        }
    }
    
    // Thêm môn học
    public void themMonHoc(){
        String tenMH = txtTenMonHoc.getText().trim();
        String maMH = txtMaMonHoc.getText().trim();
        String soTCString = txtSoTC.getText().trim();
        Integer soTC = 0;
        
        try{
            soTC = Integer.parseInt(soTCString);
            if (maMH.length() < 1 || tenMH.length() < 1){
                throw new Exception();
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(rootPane, "Dữ liệu nhập vào chưa hợp lệ !");
        }
        
        MonHoc monTinChi = new MonTinChi(listMonHocDK, maVien, tenMH, maMH, soTC, new ArrayList<DiemMonHoc>(), new ArrayList<>());
        
        ArrayList<KhoaVien> listKhoaVien = fileKhoaVien.docFileKhoaVien();
        ArrayList<MonHoc> listMonHoc = null;
        int k = 0; // Lưu vị trí của khoa viện hiện tại
        for (int i = 0; i< listKhoaVien.size(); i++){
            if (listKhoaVien.get(i).getMaKhoaVien().equals(maVien)){
                listMonHoc = listKhoaVien.get(i).getDsMonHoc();
                k = i;
            }
        }
        listMonHoc.add(monTinChi);
        listKhoaVien.get(k).setDsMonHoc(listMonHoc);
        fileKhoaVien.ghiFileKhoaVien(listKhoaVien);
        
        JOptionPane.showMessageDialog(rootPane, "Thêm thành công !");
        initComboBoxTenMonHoc();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnThemMonDK;
    private javax.swing.JButton btnThemMonHoc;
    private javax.swing.JButton btnThoat;
    private javax.swing.JComboBox<String> cbTenMonHoc;
    private javax.swing.JCheckBox checkboxDK;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtMaMonHoc;
    private javax.swing.JTextField txtMaVien;
    private javax.swing.JTextField txtSoTC;
    private javax.swing.JTextField txtTenMonHoc;
    // End of variables declaration//GEN-END:variables
}
