/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package graphicureinterface;

import dataaccesslayer.FileKhoaVien;
import entity.KhoaVien;
import entity.LopHoc;
import entity.LopNienChe;
import entity.LopTinChi;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author tu
 */
public class QuanLyKhoaVienGUI extends javax.swing.JFrame {

    /**
     * Creates new form QuanLyKhoaVienGUI
     */
    DefaultComboBoxModel<String> comboBoxModel;
    DefaultTableModel defaultTableModelKhoaVien;
    DefaultTableModel defaultTableModelLopHoc;
    static Vector<String> dataRowTableKhoaVien;
    
    public QuanLyKhoaVienGUI() {
        this.setVisible(true);
        this.setTitle("Quản Lý Khoa Viện");
        initComponents();
        this.setLocation(130, 60);
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        initTableKhoaVien();
        initTableLopHoc();
        rdHeTinChi.setSelected(true);
        btnCapNhatKhoaVien.setEnabled(false);
        btnCapNhatLopHoc.setEnabled(false);
        btnXoaKhoaVien.setEnabled(false);
        btnXoaLopHoc.setEnabled(false);
        initComboBox();
        //showDataTableLopHoc();
        showDataTableVien();
    }
    
    // Khởi tạo bảng lớp học
    void initTableLopHoc(){
        defaultTableModelLopHoc = new DefaultTableModel();
        defaultTableModelLopHoc.addColumn("Mã Lớp");
        defaultTableModelLopHoc.addColumn("Tên Lớp");
        defaultTableModelLopHoc.addColumn("Số Sinh Viên");
        defaultTableModelLopHoc.addColumn("Số Sinh Viên Max");
        
        tbLopHoc.setModel(defaultTableModelLopHoc);
        
    }
    
    // Do du lieu vao comboBox Ten Vien
    void initComboBox(){
        comboBoxModel = new DefaultComboBoxModel<>();
        FileKhoaVien fileKhoaVien = new FileKhoaVien();
        ArrayList<KhoaVien> listKhoaVien = fileKhoaVien.docFileKhoaVien();
        for (int i = 0; i< listKhoaVien.size(); i++){
            KhoaVien khoaVien = listKhoaVien.get(i);
            comboBoxModel.addElement(khoaVien.getTenVien());
        }
        cbKhoaVien.setModel(comboBoxModel);
    }
    
    void initTableKhoaVien(){
        defaultTableModelKhoaVien = new DefaultTableModel();
        defaultTableModelKhoaVien.addColumn("Mã Khoa");
        defaultTableModelKhoaVien.addColumn("Tên Khoa Viện");
        defaultTableModelKhoaVien.addColumn("Số TC Tốt Nghiệp");
        tbKhoaVien.setModel(defaultTableModelKhoaVien);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbKhoaVien = new javax.swing.JTable();
        btnThemKhoaVien = new javax.swing.JButton();
        btnCapNhatKhoaVien = new javax.swing.JButton();
        btnXoaKhoaVien = new javax.swing.JButton();
        btnLoadDuLieu = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbLopHoc = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        cbKhoaVien = new javax.swing.JComboBox<>();
        btnThemLopHoc = new javax.swing.JButton();
        btnCapNhatLopHoc = new javax.swing.JButton();
        btnXoaLopHoc = new javax.swing.JButton();
        rdHeTinChi = new javax.swing.JRadioButton();
        rdHeNienChe = new javax.swing.JRadioButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(254, 254, 254));

        jPanel2.setBackground(new java.awt.Color(251, 246, 246));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Khoa Viện", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 3, 18), new java.awt.Color(255, 0, 0))); // NOI18N

        tbKhoaVien.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        tbKhoaVien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbKhoaVien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbKhoaVienMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbKhoaVien);

        btnThemKhoaVien.setBackground(new java.awt.Color(254, 254, 254));
        btnThemKhoaVien.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnThemKhoaVien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGE/addNew.png"))); // NOI18N
        btnThemKhoaVien.setText("Thêm Khoa Viện");
        btnThemKhoaVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemKhoaVienActionPerformed(evt);
            }
        });

        btnCapNhatKhoaVien.setBackground(new java.awt.Color(254, 254, 254));
        btnCapNhatKhoaVien.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnCapNhatKhoaVien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGE/updateNew.png"))); // NOI18N
        btnCapNhatKhoaVien.setText("Cập nhật");
        btnCapNhatKhoaVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCapNhatKhoaVienActionPerformed(evt);
            }
        });

        btnXoaKhoaVien.setBackground(new java.awt.Color(254, 254, 254));
        btnXoaKhoaVien.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnXoaKhoaVien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGE/file_delete50x50.png"))); // NOI18N
        btnXoaKhoaVien.setText("Xóa");
        btnXoaKhoaVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaKhoaVienActionPerformed(evt);
            }
        });

        btnLoadDuLieu.setBackground(new java.awt.Color(254, 254, 254));
        btnLoadDuLieu.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnLoadDuLieu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGE/connect-icon.png"))); // NOI18N
        btnLoadDuLieu.setText("Load dữ liệu");
        btnLoadDuLieu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoadDuLieuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 483, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnLoadDuLieu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnThemKhoaVien, javax.swing.GroupLayout.DEFAULT_SIZE, 219, Short.MAX_VALUE)
                            .addComponent(btnCapNhatKhoaVien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(btnXoaKhoaVien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnThemKhoaVien, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(btnCapNhatKhoaVien, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLoadDuLieu, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnXoaKhoaVien, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel3.setBackground(new java.awt.Color(254, 247, 247));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Lớp Học", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 3, 18), new java.awt.Color(255, 0, 0))); // NOI18N

        tbLopHoc.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        tbLopHoc.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbLopHoc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbLopHocMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbLopHoc);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel3.setText("Khoa Viện : ");

        cbKhoaVien.setBackground(new java.awt.Color(254, 254, 254));
        cbKhoaVien.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        cbKhoaVien.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbKhoaVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbKhoaVienActionPerformed(evt);
            }
        });

        btnThemLopHoc.setBackground(new java.awt.Color(254, 254, 254));
        btnThemLopHoc.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnThemLopHoc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGE/addNew.png"))); // NOI18N
        btnThemLopHoc.setText("Thêm Lớp Học");
        btnThemLopHoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemLopHocActionPerformed(evt);
            }
        });

        btnCapNhatLopHoc.setBackground(new java.awt.Color(254, 254, 254));
        btnCapNhatLopHoc.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnCapNhatLopHoc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGE/updateNew.png"))); // NOI18N
        btnCapNhatLopHoc.setText("Cập nhật");
        btnCapNhatLopHoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCapNhatLopHocActionPerformed(evt);
            }
        });

        btnXoaLopHoc.setBackground(new java.awt.Color(254, 254, 254));
        btnXoaLopHoc.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnXoaLopHoc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGE/file_delete50x50.png"))); // NOI18N
        btnXoaLopHoc.setText("Xóa");
        btnXoaLopHoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaLopHocActionPerformed(evt);
            }
        });

        buttonGroup1.add(rdHeTinChi);
        rdHeTinChi.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        rdHeTinChi.setText("Hệ tín chỉ");
        rdHeTinChi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rdHeTinChiMouseClicked(evt);
            }
        });

        buttonGroup1.add(rdHeNienChe);
        rdHeNienChe.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        rdHeNienChe.setText("Hệ niên chế");
        rdHeNienChe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rdHeNienCheMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(btnCapNhatLopHoc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnThemLopHoc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(65, 65, 65)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rdHeNienChe)
                                    .addComponent(rdHeTinChi)
                                    .addComponent(btnXoaLopHoc, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 469, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(22, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cbKhoaVien, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbKhoaVien, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnThemLopHoc, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(rdHeTinChi)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rdHeNienChe)))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnXoaLopHoc, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCapNhatLopHoc, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel4.setBackground(new java.awt.Color(254, 255, 143));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGE/bk.jpg"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 30)); // NOI18N
        jLabel2.setText("QUẢN LÝ KHOA VIỆN");

        jButton2.setBackground(new java.awt.Color(254, 254, 254));
        jButton2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGE/logout-512.png"))); // NOI18N
        jButton2.setText("Thoát");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(231, 231, 231)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton2)
                        .addComponent(jLabel2)))
                .addGap(23, 23, 23))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnThemKhoaVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemKhoaVienActionPerformed
        // TODO add your handling code here:
        new ThemKhoaVienGUI();
    }//GEN-LAST:event_btnThemKhoaVienActionPerformed

    private void btnCapNhatKhoaVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCapNhatKhoaVienActionPerformed
        // TODO add your handling code here:
        capNhat();
        showDataTableVien();
    }//GEN-LAST:event_btnCapNhatKhoaVienActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btnLoadDuLieuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoadDuLieuActionPerformed
        // TODO add your handling code here:
        showDataTableVien();
        initComboBox();
    }//GEN-LAST:event_btnLoadDuLieuActionPerformed

    private void tbKhoaVienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbKhoaVienMouseClicked
        // TODO add your handling code here:
        btnCapNhatKhoaVien.setEnabled(true);
        btnXoaKhoaVien.setEnabled(true);
    }//GEN-LAST:event_tbKhoaVienMouseClicked

    private void btnXoaKhoaVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaKhoaVienActionPerformed
        // TODO add your handling code here:
        xoaVien();
        showDataTableVien();
    }//GEN-LAST:event_btnXoaKhoaVienActionPerformed

    private void btnThemLopHocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemLopHocActionPerformed
        // TODO add your handling code here:
        themLopHoc();
        showDataTableLopHoc();
    }//GEN-LAST:event_btnThemLopHocActionPerformed

    private void cbKhoaVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbKhoaVienActionPerformed
        // TODO add your handling code here:
        showDataTableLopHoc();
    }//GEN-LAST:event_cbKhoaVienActionPerformed

    private void btnCapNhatLopHocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCapNhatLopHocActionPerformed
        // TODO add your handling code here:
        capNhatLopHoc();
        showDataTableLopHoc();
    }//GEN-LAST:event_btnCapNhatLopHocActionPerformed

    private void tbLopHocMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbLopHocMouseClicked
        // TODO add your handling code here:
        btnCapNhatLopHoc.setEnabled(true);
        btnXoaLopHoc.setEnabled(true);
    }//GEN-LAST:event_tbLopHocMouseClicked

    private void btnXoaLopHocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaLopHocActionPerformed
        // TODO add your handling code here:
        xoaLopHoc();
        showDataTableLopHoc();
    }//GEN-LAST:event_btnXoaLopHocActionPerformed

    private void rdHeTinChiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rdHeTinChiMouseClicked
        // TODO add your handling code here:
        showDataTableLopHoc();
    }//GEN-LAST:event_rdHeTinChiMouseClicked

    private void rdHeNienCheMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rdHeNienCheMouseClicked
        // TODO add your handling code here:
        showDataTableLopHoc();
    }//GEN-LAST:event_rdHeNienCheMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuanLyKhoaVienGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuanLyKhoaVienGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuanLyKhoaVienGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuanLyKhoaVienGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QuanLyKhoaVienGUI().setVisible(true);
            }
        });
    }
    
    void showDataTableVien(){
        FileKhoaVien fileKhoaVien = new FileKhoaVien();
        ArrayList<KhoaVien> listKhoaVien= fileKhoaVien.docFileKhoaVien();
        defaultTableModelKhoaVien.setNumRows(0);
        for (int i = 0; i< listKhoaVien.size(); i++){
            KhoaVien khoaVien = listKhoaVien.get(i);
            Vector<String> dataRow = new Vector<>();
            dataRow.add(khoaVien.getMaKhoaVien());
            dataRow.add(khoaVien.getTenVien());
            dataRow.add(String.valueOf(khoaVien.getSoTCTN()));
            defaultTableModelKhoaVien.addRow(dataRow);
        }
    }
    
    void capNhat(){
        CapNhatKhoaVienGUI.dataRow = (Vector<String>) defaultTableModelKhoaVien.getDataVector().elementAt(tbKhoaVien.getSelectedRow());
        new CapNhatKhoaVienGUI();
    }
    
    void xoaVien(){
        FileKhoaVien fileKhoaVien = new FileKhoaVien();
        ArrayList<KhoaVien> listKhoaVien = fileKhoaVien.docFileKhoaVien();
        
        // Lấy ra dòng dữ liệu được chọn trong bảng
        dataRowTableKhoaVien = (Vector<String>) defaultTableModelKhoaVien.getDataVector().elementAt(tbKhoaVien.getSelectedRow());
        for (int i = 0; i< listKhoaVien.size(); i++){
            KhoaVien khoaVien  = listKhoaVien.get(i);
            if (dataRowTableKhoaVien.get(0).equals(khoaVien.getMaKhoaVien())){
                listKhoaVien.remove(i);
                fileKhoaVien.ghiFileKhoaVien(listKhoaVien);
            }
        }
        
    }
    
    void themLopHoc(){
        String tenVien = cbKhoaVien.getSelectedItem().toString();
        FileKhoaVien fileKhoaVien = new FileKhoaVien();
        
        ArrayList<KhoaVien> listKhoaVien = fileKhoaVien.docFileKhoaVien();
        
        // Tìm mã viện có tên viện là tenVien
        for (int i = 0; i< listKhoaVien.size(); i++){
            KhoaVien khoaVien = listKhoaVien.get(i);
            if (khoaVien.getTenVien().equals(tenVien)){
                ThemLopHocGUI.maVien = khoaVien.getMaKhoaVien();
            }
        }
        if (rdHeTinChi.isSelected()){
            ThemLopHocGUI.rdTinChi = 1;
        }else {
            ThemLopHocGUI.rdTinChi = 0;
        }
        new ThemLopHocGUI();
    }
    
    
    // Đổ dữ liệu vào bảng lớp học
    void showDataTableLopHoc(){
        defaultTableModelLopHoc.setNumRows(0);
        FileKhoaVien fileKhoaVien = new FileKhoaVien();
        ArrayList<KhoaVien> listKhoaVien = fileKhoaVien.docFileKhoaVien();
        ArrayList<LopHoc> listLopHoc = null;
        
        String tenVien = cbKhoaVien.getSelectedItem().toString();
        
        // Lấy ra danh sách lớp học
        for (int i = 0; i< listKhoaVien.size(); i++){
            if (listKhoaVien.get(i).getTenVien().equals(tenVien)){
                listLopHoc = listKhoaVien.get(i).getDsLopHoc();
            }
        }
        
        if(rdHeTinChi.isSelected()){
            for (int i = 0; i< listLopHoc.size(); i++){
                LopHoc lopHoc = listLopHoc.get(i);
                if (lopHoc instanceof LopTinChi){
                    Vector<String> data = new Vector<>();
                    data.add(String.valueOf(lopHoc.getMaLop()));
                    data.add(lopHoc.getTenLop());
                    data.add(String.valueOf(lopHoc.getSoSV()));
                    data.add(String.valueOf(lopHoc.getSO_SV_MAX()));
                    defaultTableModelLopHoc.addRow(data);
                }
            }
        }else {
            for (int i = 0; i< listLopHoc.size(); i++){
                LopHoc lopHoc = listLopHoc.get(i);
                if (lopHoc instanceof LopNienChe){
                    Vector<String> data = new Vector<>();
                    data.add(String.valueOf(lopHoc.getMaLop()));
                    data.add(lopHoc.getTenLop());
                    data.add(String.valueOf(lopHoc.getSoSV()));
                    data.add(String.valueOf(lopHoc.getSO_SV_MAX()));
                    defaultTableModelLopHoc.addRow(data);
                }                
            }            
        }
        
    }
    
    
    // Xử lý sự kiện btnCapNhatLopHoc
    // Cập nhật thông tin lớp học được chọn từ bảng lớp học
    void capNhatLopHoc(){
        String tenVien = cbKhoaVien.getSelectedItem().toString();
        FileKhoaVien fileKhoaVien = new FileKhoaVien();
        ArrayList<KhoaVien> listKhoaVien = fileKhoaVien.docFileKhoaVien();
        for (int i = 0; i< listKhoaVien.size(); i++){
            KhoaVien khoaVien = listKhoaVien.get(i);
            if (khoaVien.getTenVien().equals(tenVien)){
                CapNhatLopHocGUI.maVien = khoaVien.getMaKhoaVien();
            }
        }
        
        CapNhatLopHocGUI.data = (Vector<String>) defaultTableModelLopHoc.getDataVector().elementAt(tbLopHoc.getSelectedRow());
        new CapNhatLopHocGUI();
    }
    
    // xử lý sự kiện xóa lớp học
    void xoaLopHoc(){        
        FileKhoaVien fileKhoaVien = new FileKhoaVien();
        ArrayList<KhoaVien> listKhoaVien = fileKhoaVien.docFileKhoaVien();
        ArrayList<LopHoc> listLopHoc = null;
        
        String tenVien = cbKhoaVien.getSelectedItem().toString();
        int k = 0; // Lưu vị trí của khoa Viện có lớp bị xóa
        
        for (int i = 0; i< listKhoaVien.size(); i++){
            if (listKhoaVien.get(i).getTenVien().equals(tenVien)){
                k = i;
                listLopHoc = listKhoaVien.get(i).getDsLopHoc();
            }
        }
        
        // Lấy dòng dữ liệu được chọn từ bảng lơp học
        Vector<String> dataRow = (Vector<String>) defaultTableModelLopHoc.getDataVector().elementAt(tbLopHoc.getSelectedRow());
        
        for (int i = 0; i< listLopHoc.size(); i++){
            if (listLopHoc.get(i).getMaLop() == Integer.parseInt(dataRow.get(0))){
                listLopHoc.remove(i);
            }
        }
        
        listKhoaVien.get(k).setDsLopHoc(listLopHoc);
        fileKhoaVien.ghiFileKhoaVien(listKhoaVien);
        JOptionPane.showMessageDialog(rootPane, "Xóa thành công !");
        
        // Hiển thị dữ liệu mới ra bảng
        showDataTableLopHoc();
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCapNhatKhoaVien;
    private javax.swing.JButton btnCapNhatLopHoc;
    private javax.swing.JButton btnLoadDuLieu;
    private javax.swing.JButton btnThemKhoaVien;
    private javax.swing.JButton btnThemLopHoc;
    private javax.swing.JButton btnXoaKhoaVien;
    private javax.swing.JButton btnXoaLopHoc;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cbKhoaVien;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JRadioButton rdHeNienChe;
    private javax.swing.JRadioButton rdHeTinChi;
    private javax.swing.JTable tbKhoaVien;
    private javax.swing.JTable tbLopHoc;
    // End of variables declaration//GEN-END:variables
}
