/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package graphicureinterface;

import dataaccesslayer.FileKhoaVien;
import dataaccesslayer.FileSinhVien;
import entity.KhoaVien;
import entity.LopHoc;
import entity.SinhVien;
import entity.SinhVienTinChi;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author tu
 */
public class SinhVienGUI extends javax.swing.JFrame {

    /**
     * Creates new form SinhVienGUI
     */
    public FileKhoaVien fileKhoaVien;
    public FileSinhVien fileSinhVien;
    public static String user;
    public static String ms;
    public SinhVienGUI() {
        this.setVisible(true);
        this.setTitle("Giành cho sinh viên");
        initComponents();
        this.setLocation(300, 100);
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        lbUser.setText(user);
        lbMSSV.setText(ms);
    }
    
    public void dangKiHocTap(){
        ArrayList<SinhVien> listSinhVien = new ArrayList<>();
        fileSinhVien = new FileSinhVien();
        SinhVien sv = null;
        listSinhVien = fileSinhVien.docFileSinhVien();
        
        for (SinhVien sinhVien : listSinhVien) {
            if (sinhVien.getMaSV().equals(ms)){
                sv = sinhVien;
            }
        }
        
        if (sv instanceof SinhVienTinChi){
            DangKiHocGUI.sv = sv;
            new DangKiHocGUI();
        }else {
            DangKiHocNienCheGUI.sv = sv;
            new DangKiHocNienCheGUI();
        }
    }
    
    public void xemKetQua(){
        ArrayList<SinhVien> listSinhVien = new ArrayList<>();
        fileSinhVien = new FileSinhVien();
        
        listSinhVien = fileSinhVien.docFileSinhVien();
        
        for (SinhVien sinhVien : listSinhVien) {
            if (sinhVien.getMaSV().equals(ms)){
                KetQuaHocTapGUI.sv = sinhVien;
            }
        }
        
        new KetQuaHocTapGUI();
    }
    
    public void xemThongTin(){
        ArrayList<SinhVien> listSinhVien = new ArrayList<>();
        fileSinhVien = new FileSinhVien();
        
        listSinhVien = fileSinhVien.docFileSinhVien();
        
        for (SinhVien sinhVien : listSinhVien) {
            if (sinhVien.getMaSV().equals(ms)){
                ThongTinCaNhanGUI.sv = sinhVien;
            }
        }
        
        new ThongTinCaNhanGUI();
    }
    
    public void xemBangDiem(){
        fileSinhVien = new FileSinhVien();
        ArrayList<SinhVien> listSinhVien = fileSinhVien.docFileSinhVien();
        SinhVien sv = null;
        for (SinhVien sinhVien : listSinhVien) {
            if (sinhVien.getMaSV().equals(ms)){
                sv = sinhVien;
            }
        }
        if (sv instanceof SinhVienTinChi){
            KetQuaHocTapGUI.sv = sv;
            new KetQuaHocTapGUI();
        }else {
            KetQuaHocTapNienCheGUI.sv = sv;
            new KetQuaHocTapNienCheGUI();
        }
    }
    
    public void xetTotNghiep(){
        fileKhoaVien = new FileKhoaVien();
        ArrayList<KhoaVien> listKhoaVien  = new ArrayList<>();
        ArrayList<LopHoc> listLopHoc = new ArrayList<>();
        
        listKhoaVien = fileKhoaVien.docFileKhoaVien();
        for (LopHoc lopHoc : listLopHoc) {
            
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        btnThongTinCaNhan = new javax.swing.JButton();
        btnKetQuaHocTap = new javax.swing.JButton();
        btnDangKiHocTap = new javax.swing.JButton();
        btnXetTotNghiep = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        lbUser = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lbMSSV = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(254, 254, 254));

        jPanel2.setBackground(new java.awt.Color(254, 255, 143));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0)));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGE/bk.jpg"))); // NOI18N

        jButton1.setBackground(new java.awt.Color(254, 254, 254));
        jButton1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGE/logout-512.png"))); // NOI18N
        jButton1.setText("Thoát");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel2.setText("HỆ THỐNG THÔNG TIN SINH VIÊN");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jButton1)
                .addComponent(jLabel2))
        );

        jPanel3.setBackground(new java.awt.Color(254, 254, 254));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Bảng điều khiển", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 18), new java.awt.Color(255, 0, 0))); // NOI18N

        btnThongTinCaNhan.setBackground(new java.awt.Color(254, 254, 254));
        btnThongTinCaNhan.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnThongTinCaNhan.setText("Thông Tin Cá Nhân");
        btnThongTinCaNhan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThongTinCaNhanActionPerformed(evt);
            }
        });

        btnKetQuaHocTap.setBackground(new java.awt.Color(254, 254, 254));
        btnKetQuaHocTap.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnKetQuaHocTap.setText("Kết Quả Học Tập");
        btnKetQuaHocTap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKetQuaHocTapActionPerformed(evt);
            }
        });

        btnDangKiHocTap.setBackground(new java.awt.Color(254, 254, 254));
        btnDangKiHocTap.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnDangKiHocTap.setText("Đăng Kí Học Tâp ");
        btnDangKiHocTap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDangKiHocTapActionPerformed(evt);
            }
        });

        btnXetTotNghiep.setBackground(new java.awt.Color(254, 254, 254));
        btnXetTotNghiep.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnXetTotNghiep.setText("Yêu cầu xét TN");
        btnXetTotNghiep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXetTotNghiepActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnThongTinCaNhan, javax.swing.GroupLayout.DEFAULT_SIZE, 205, Short.MAX_VALUE)
                    .addComponent(btnKetQuaHocTap, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnDangKiHocTap, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnXetTotNghiep, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(52, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(btnThongTinCaNhan, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnKetQuaHocTap, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnDangKiHocTap, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(btnXetTotNghiep, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(46, Short.MAX_VALUE))
        );

        jLabel3.setFont(new java.awt.Font("Times New Roman", 3, 15)); // NOI18N
        jLabel3.setText("Xin chào bạn : ");

        lbUser.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        lbUser.setText("user");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jLabel4.setText("MSSV : ");

        lbMSSV.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        lbMSSV.setText("ms");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbMSSV)
                    .addComponent(lbUser)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(lbUser))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(lbMSSV))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new DangNhapGUI();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnDangKiHocTapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDangKiHocTapActionPerformed
        // TODO add your handling code here:
        dangKiHocTap();
    }//GEN-LAST:event_btnDangKiHocTapActionPerformed

    private void btnThongTinCaNhanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThongTinCaNhanActionPerformed
        // TODO add your handling code here:
        xemThongTin();
    }//GEN-LAST:event_btnThongTinCaNhanActionPerformed

    private void btnKetQuaHocTapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKetQuaHocTapActionPerformed
        // TODO add your handling code here:
        xemBangDiem();
    }//GEN-LAST:event_btnKetQuaHocTapActionPerformed

    private void btnXetTotNghiepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXetTotNghiepActionPerformed
        // TODO add your handling code here:
        xetTotNghiep();
    }//GEN-LAST:event_btnXetTotNghiepActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SinhVienGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SinhVienGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SinhVienGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SinhVienGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SinhVienGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDangKiHocTap;
    private javax.swing.JButton btnKetQuaHocTap;
    private javax.swing.JButton btnThongTinCaNhan;
    private javax.swing.JButton btnXetTotNghiep;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lbMSSV;
    private javax.swing.JLabel lbUser;
    // End of variables declaration//GEN-END:variables
}
